version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "apigw-sfn-lambda-callback"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-lwdez15vpwl6"
s3_prefix = "ChildWorkflow"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
