version = 0.1
[marquesh]
[marquesh.deploy]
[marquesh.deploy.parameters]
stack_name = "sfn-apig"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-lwdez15vpwl6"
s3_prefix = "sfn-apig"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"

[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "sam-app"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-tlh5lnyjvxx4"
s3_prefix = "sam-app"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
